[default]
marketplace_project = 'revieve-public' # This should be set to the name of the project you want to use, otherwise an error will be thrown.
auto_approve_entitlements = false  # This should be set to true if you want to auto-approve entitlements.
event_topic = 'projects/cloudcommerceproc-prod/topics/revieve-public'         # Optional. The name of the topic to publish events to.
slack_webhook = 'https://hooks.slack.com/services/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'       # Optional. The webhook URL to send Slack messages to.
audience = 'api.gcpmarketplace.revieve.com'

[global] # global will override everything
is_codelab = false
